title: soroush safari
description: soroush safari / Exploring python & Things.

author: soroush safari
email: soroush_safarii@yahoo.com
timezone: +03:30

url: https://imgod.ir/
root: /
static: /static


post_num: all
archive_post_num: all
feed_output: atom.xml

default_floor: fa
default_markup: mmd

disqus_shortname: cocii

template: sallar

 
 

twitter: https://twitter.com/soroush_safarii
github: https://github.com/coci
