title: soroush safari
description: soroush safari's Blog. Exploring python & Things.
author: soroush safari
language: English

url: https://imgod.ir/blog
root: /blog

default_extension: md

permalink: :title/

template: sallar

lists:
