title: soroush safari
description: soroush safari's Blog. Exploring python & Things.
author: soroush safari
language: English

url: https://3nzo.com/blog
root: /blog

static: /static/
imageurl: /img/

default_extension: md

permalink: :title/

template: sallar
disqus_shortname: cocii

lists:
