title: سروش صفری
description: سلام ، این وبلاگ منه
author: سروش صفری
language: Farsi

url: https://thecoci.me/farsi/
root: /farsi/

default_extension: md

permalink: :title/

template: sallar

lists:

namespace:

plugins:
 - Jdate
