title: سروش صفری
description: سلام ، این وبلاگ منه
author: سروش صفری
language: Farsi

url: https://imgod.ir/swift/
root: /swift/

default_extension: md

permalink: :title/

template: sallar

lists:

namespace:

plugins:
 - Jdate
